package cmd

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"github.com/BurntSushi/toml"

	"github.com/webkaz-labs/kagikae/internal/config"
	"github.com/webkaz-labs/kagikae/internal/constants"
	"github.com/webkaz-labs/kagikae/internal/paths"
)

func (app *App) ownedUninstallFragment(dir, content string) bool {
	info := parseDirFragment(content)
	if (info.Profile != "" && !config.ValidName(info.Profile)) || (info.Mode != modeShared && info.Mode != modeIsolated) {
		return false
	}
	for tool, account := range info.Accounts {
		if !constants.IsTool(tool) || !config.ValidName(account) {
			return false
		}
	}
	var targets []runTarget
	for _, tool := range constants.Tools {
		if account, ok := info.Accounts[tool]; ok {
			targets = append(targets, runTarget{Tool: tool, Account: account})
		}
	}
	entries := app.bondIsolationEntries(targets, paths.PinID(dir))
	if info.Mode == modeIsolated {
		entries = app.pinIsolationEntries(targets, paths.PinID(dir))
	}
	for i := range entries {
		if _, present := info.CredDirs[entries[i].Tool]; !present {
			entries[i].CredEnvVar, entries[i].CredDir = "", ""
		}
	}
	companions, redactions, _, err := app.companionPlan(info.Profile)
	if err != nil {
		return false
	}
	return content == renderDirFragment(info.Profile, info.Mode, entries, companionFragmentLines(companions), redactions)
}

func (app *App) uninstallProjectRemainder(content string) ([]byte, bool) {
	if strings.Count(content, miseBlockStart) != 1 || strings.Count(content, miseBlockEnd) != 1 {
		return nil, false
	}
	var parsed struct {
		Env map[string]string `toml:"env"`
	}
	if _, err := toml.Decode(content, &parsed); err != nil {
		return nil, false
	}
	profile := parsed.Env[constants.EnvKaeProfile]
	if !config.ValidName(profile) {
		return nil, false
	}
	for _, auto := range []bool{false, true} {
		block := app.miseBlock(profile, auto)
		at := strings.Index(content, block)
		if at < 0 || (at > 0 && content[at-1] != '\n') || !miseTableEndsBeforeContent(content[at+len(block):]) {
			continue
		}
		// Exact generated bytes alone could be inside a multiline string. Compare
		// the semantic tables before removal, as the completion recognizer does.
		var actual, generated map[string]any
		if _, err := toml.Decode(content, &actual); err != nil {
			return nil, false
		}
		if _, err := toml.Decode(block, &generated); err != nil {
			return nil, false
		}
		expected, matches := uninstallTableRemainder(actual, generated)
		if !matches {
			continue
		}
		remaining := strings.Replace(content, block, "", 1)
		var clean map[string]any
		if _, err := toml.Decode(remaining, &clean); err != nil {
			return nil, false
		}
		if !reflect.DeepEqual(clean, expected) {
			return nil, false
		}
		return []byte(remaining), true
	}
	return nil, false
}

func uninstallTableRemainder(actual, generated map[string]any) (map[string]any, bool) {
	remaining := make(map[string]any, len(actual))
	for key, value := range actual {
		remaining[key] = value
	}
	for key, expected := range generated {
		got, exists := remaining[key]
		if !exists {
			return nil, false
		}
		if table, ok := expected.(map[string]any); ok {
			gotTable, ok := got.(map[string]any)
			if !ok {
				return nil, false
			}
			rest, ok := uninstallTableRemainder(gotTable, table)
			if !ok {
				return nil, false
			}
			if len(rest) > 0 {
				remaining[key] = rest
				continue
			}
		} else if !reflect.DeepEqual(got, expected) {
			return nil, false
		}
		delete(remaining, key)
	}
	return remaining, true
}

func uninstallCompletionPaths(app *App) map[string][]string {
	xdgConfig := paths.XDGConfigHome(app.Env.Getenv, app.Env.Home, "")
	xdgData := paths.XDGDataHome(app.Env.Getenv, app.Env.Home, "")
	return map[string][]string{
		"bash": {filepath.Join(xdgData, "bash-completion", "completions", "kae")},
		"fish": {filepath.Join(xdgConfig, "fish", "completions", "kae.fish")},
		"zsh": {
			filepath.Join(xdgConfig, "zsh", "completions", "_kae"),
			filepath.Join(app.Env.Home, ".zsh", "completions", "_kae"),
			filepath.Join(app.Env.Home, ".zfunc", "_kae"),
			filepath.Join(xdgData, "zsh", "site-functions", "_kae"),
		},
	}
}

func (app *App) inspectUninstallGlobal(p *uninstallPlan) {
	journal := filepath.Join(app.Paths.StateDir, "mise-completion-migration.json")
	if _, err := os.Lstat(journal); err == nil || !os.IsNotExist(err) {
		p.unresolved(constants.UninstallGlobal, journal, constants.UninstallMigration)
		p.report.Manual = append(p.report.Manual, "Resolve the outstanding completion migration before uninstalling; cleanup does not run completion refresh or recreate hooks.")
		return
	}
	st, err := app.loadState()
	if err != nil {
		p.unresolved(constants.UninstallGlobal, app.Paths.StateFile(), constants.UninstallInvalidData)
		return
	}
	before := len(p.operations)
	p.inspectFile(constants.UninstallGlobal, app.Paths.MiseGlobalFragmentFile(), "", func(content string) ([]byte, bool) {
		isolated, _, _, err := splitGlobalMise(content)
		if err != nil {
			return nil, false
		}
		if isolated == "" {
			return nil, len(st.Synced) == 0
		}
		expected := app.renderGlobalFragment(st.Synced)
		if len(st.Synced) == 0 {
			// After state was cleared but before the derived file was removed,
			// infer only account paths the generator itself can reproduce.
			var parsed struct {
				Env map[string]string `toml:"env"`
			}
			if _, err := toml.Decode(isolated, &parsed); err != nil {
				return nil, false
			}
			inferred := map[string]string{}
			for _, tool := range constants.Tools {
				value := parsed.Env[isolationEnvVar(tool)]
				if value == "" {
					continue
				}
				account := filepath.Base(value)
				if !config.ValidName(account) || value != app.Paths.GlobalIsolatedHomeDir(tool, account) {
					return nil, false
				}
				inferred[tool] = account
			}
			expected = app.renderGlobalFragment(inferred)
		}
		isolated = strings.Replace(isolated, legacyGlobalIsolatedOwnershipLine, globalIsolatedOwnershipLine, 1)
		return nil, isolated == expected
	})
	if len(p.operations) > before {
		p.operations[len(p.operations)-1].synced = st.Synced
	}
	if len(st.Synced) != 0 {
		if _, err := os.Lstat(app.Paths.MiseGlobalFragmentFile()); os.IsNotExist(err) {
			p.unresolved(constants.UninstallGlobal, app.Paths.StateFile(), constants.UninstallInvalidData)
		}
	}
	p.inspectFile(constants.UninstallLegacy, globalMiseConfigPath(app.Env), "", func(content string) ([]byte, bool) {
		_, block := knownCompletion(content)
		if block == "" {
			return nil, false
		}
		return []byte(strings.Replace(content, block, "", 1)), true
	})
}
