// Package git declares the git companion: it binds git's commit identity
// (user.email/name/signingkey) per profile via a kae-owned global config file.
package git

import (
	"github.com/webkaz-labs/kagikae/internal/companion"
	"github.com/webkaz-labs/kagikae/internal/constants"
)

// configTmpl renders the kae-owned global git config. When GIT_CONFIG_GLOBAL is
// set git stops auto-reading ~/.gitconfig, so the file explicitly [include]s
// the user's own config (aliases, core.*, etc. survive) and then overrides only
// the identity fields. ~/.gitconfig itself is never modified; the override is
// scoped to the pinned directory by the mise fragment and reverts on unpin.
const configTmpl = `# kagikae-managed — generated by kae, do not edit by hand.
{{- if .HomeGitconfig}}
[include]
	path = {{.HomeGitconfig}}
{{- end}}
[user]
{{- if .email}}
	email = {{.email}}
{{- end}}
{{- if .name}}
	name = {{.name}}
{{- end}}
{{- if .signingkey}}
	signingkey = {{.signingkey}}
{{- end}}
`

func init() {
	companion.Register(companion.Spec{
		ID:         constants.CompanionGit,
		Binary:     "git",
		Kind:       companion.KindGitConfig,
		Knobs:      []companion.Knob{{Name: "email"}, {Name: "name"}, {Name: "signingkey"}},
		FileTmpl:   configTmpl,
		FileEnvVar: "GIT_CONFIG_GLOBAL",
	})
}
